import 'deck_data.dart';

class CapitalsDeck{
  static List<Flashcard> capitalFlashcards = [
    Flashcard.fromPlainText('Nepal', 'Kathmandu'),
    Flashcard.fromPlainText('Dominican Republic', 'Santo Domingo'),
    Flashcard.fromPlainText('Hungary', 'Budapest'),
    Flashcard.fromPlainText('Philippines', 'Manila'),
    Flashcard.fromPlainText('Lesotho', 'Maseru'),
    Flashcard.fromPlainText('Moldova', 'Chisinau'),
    Flashcard.fromPlainText('Tajikistan', 'Dushanbe'),
    Flashcard.fromPlainText('India', 'New Delhi'),
    Flashcard.fromPlainText('Serbia', 'Belgrade'),
    Flashcard.fromPlainText('Paraguay', 'Asuncion'),
    Flashcard.fromPlainText('Syria', 'Damascus'),
    Flashcard.fromPlainText('Jordan', 'Amman'),
    Flashcard.fromPlainText('Equatorial Guinea', 'Malabo'),
    Flashcard.fromPlainText('Haiti', 'Port au Prince'),
    Flashcard.fromPlainText('Guyana', 'Georgetown'),
    Flashcard.fromPlainText('Saudi Arabia', 'Riyadh'),
    Flashcard.fromPlainText('Kuwait', 'Kuwait City'),
    Flashcard.fromPlainText('Iran', 'Tehran'),
    Flashcard.fromPlainText('Bosnia and Herzegovina', 'Sarajevo'),
    Flashcard.fromPlainText('Cape Verde', 'Praia'),
    Flashcard.fromPlainText('Mexico', 'Mexico City'),
    Flashcard.fromPlainText('Malaysia', 'Kuala Lumpur'),
    Flashcard.fromPlainText('Finland', 'Helsinki'),
    Flashcard.fromPlainText('Pakistan', 'Islamabad'),
    Flashcard.fromPlainText('Brazil', 'Brasilia'),
    Flashcard.fromPlainText('Samoa', 'Apia'),
    Flashcard.fromPlainText('Bhutan', 'Thimphu'),
    Flashcard.fromPlainText('Honduras', 'Tegucigalpa'),
    Flashcard.fromPlainText('Guinea-Bissau', 'Bissau'),
    Flashcard.fromPlainText('Canada', 'Ottawa'),
    Flashcard.fromPlainText('Venezuela', 'Caracas'),
    Flashcard.fromPlainText('Madagascar', 'Antananarivo'),
    Flashcard.fromPlainText('El Salvador', 'San Salvador'),
    Flashcard.fromPlainText('Dominica', 'Roseau'),
    Flashcard.fromPlainText('Seychelles', 'Victoria'),
    Flashcard.fromPlainText('Kiribati', 'Tarawa Atoll'),
    Flashcard.fromPlainText('North Macedonia (Macedonia)[15]', 'Skopje'),
    Flashcard.fromPlainText('United Kingdom', 'London'),
    Flashcard.fromPlainText('Namibia', 'Windhoek'),
    Flashcard.fromPlainText('Saint Lucia', 'Castries'),
    Flashcard.fromPlainText('Czech Republic (Czechia)[5]', 'Prague'),
    Flashcard.fromPlainText('Ecuador', 'Quito'),
    Flashcard.fromPlainText('Kenya', 'Nairobi'),
    Flashcard.fromPlainText('Eritrea', 'Asmara'),
    Flashcard.fromPlainText('Egypt', 'Cairo'),
    Flashcard.fromPlainText('Grenada', 'Saint George\'s'),
    Flashcard.fromPlainText('Ethiopia', 'Addis Ababa'),
    Flashcard.fromPlainText('Guinea', 'Conakry'),
    Flashcard.fromPlainText('Niger', 'Niamey'),
    Flashcard.fromPlainText('Poland', 'Warsaw'),
    Flashcard.fromPlainText('South Africa', 'Pretoria, Bloemfontein, Cape Town'),
    Flashcard.fromPlainText('Australia', 'Canberra'),
    Flashcard.fromPlainText('Lithuania', 'Vilnius'),
    Flashcard.fromPlainText('Suriname', 'Paramaribo'),
    Flashcard.fromPlainText('Sierra Leone', 'Freetown'),
    Flashcard.fromPlainText('Solomon Islands', 'Honiara'),
    Flashcard.fromPlainText('Angola', 'Luanda'),
    Flashcard.fromPlainText('Latvia', 'Riga'),
    Flashcard.fromPlainText('Thailand', 'Bangkok'),
    Flashcard.fromPlainText('East Timor', 'Dili'),
    Flashcard.fromPlainText('Myanmar (Burma)', 'Nay Pyi Taw'),
    Flashcard.fromPlainText('France', 'Paris'),
    Flashcard.fromPlainText('Zimbabwe', 'Harare'),
    Flashcard.fromPlainText('Estonia', 'Tallinn'),
    Flashcard.fromPlainText('Georgia', 'Tbilisi'),
    Flashcard.fromPlainText('Guatemala', 'Guatemala City'),
    Flashcard.fromPlainText('Cameroon', 'Yaounde'),
    Flashcard.fromPlainText('Bahamas', 'Nassau'),
    Flashcard.fromPlainText('Montenegro', 'Podgorica'),
    Flashcard.fromPlainText('Scotland[19]', 'Edinburgh'),
    Flashcard.fromPlainText('Uzbekistan', 'Tashkent'),
    Flashcard.fromPlainText('Norway', 'Oslo'),
    Flashcard.fromPlainText('Liechtenstein', 'Vaduz'),
    Flashcard.fromPlainText('Morocco', 'Rabat'),
    Flashcard.fromPlainText('Spain', 'Madrid'),
    Flashcard.fromPlainText('United States', 'Washington D.C.'),
    Flashcard.fromPlainText('Panama', 'Panama City'),
    Flashcard.fromPlainText('Tonga', 'Nuku\'alofa'),
    Flashcard.fromPlainText('Benin', 'Porto Novo'),
    Flashcard.fromPlainText('Belize', 'Belmopan'),
    Flashcard.fromPlainText('Afghanistan', 'Kabul'),
    Flashcard.fromPlainText('Federated States of Micronesia', 'Palikir'),
    Flashcard.fromPlainText('Cambodia', 'Phnom Penh'),
    Flashcard.fromPlainText('Burundi', 'Gitega'),
    Flashcard.fromPlainText('Wales[26]', 'Cardiff'),
    Flashcard.fromPlainText('Congo, Democratic Republic of the', 'Kinshasa'),
    Flashcard.fromPlainText('Costa Rica', 'San Jose'),
    Flashcard.fromPlainText('Djibouti', 'Djibouti'),
    Flashcard.fromPlainText('Tuvalu', 'Funafuti'),
    Flashcard.fromPlainText('Uruguay', 'Montevideo'),
    Flashcard.fromPlainText('Andorra', 'Andorra la Vella'),
    Flashcard.fromPlainText('Iceland', 'Reykjavik'),
    Flashcard.fromPlainText('Mali', 'Bamako'),
    Flashcard.fromPlainText('Sweden', 'Stockholm'),
    Flashcard.fromPlainText('Libya', 'Tripoli'),
    Flashcard.fromPlainText('Mauritius', 'Port Louis'),
    Flashcard.fromPlainText('Singapore', 'Singapore'),
    Flashcard.fromPlainText('Malta', 'Valletta'),
    Flashcard.fromPlainText('Togo', 'Lome'),
    Flashcard.fromPlainText('Saint Vincent and the Grenadines', 'Kingstown'),
    Flashcard.fromPlainText('Central African Republic', 'Bangui'),
    Flashcard.fromPlainText('Gambia', 'Banjul'),
    Flashcard.fromPlainText('Mozambique', 'Maputo'),
    Flashcard.fromPlainText('Netherlands', 'Amsterdam'),
    Flashcard.fromPlainText('Mongolia', 'Ulaanbaatar'),
    Flashcard.fromPlainText('Papua New Guinea', 'Port Moresby'),
    Flashcard.fromPlainText('Maldives', 'Male'),
    Flashcard.fromPlainText('Congo, Republic of the', 'Brazzaville'),
    Flashcard.fromPlainText('Senegal', 'Dakar'),
    Flashcard.fromPlainText('Kyrgyzstan', 'Bishkek'),
    Flashcard.fromPlainText('Ghana', 'Accra'),
    Flashcard.fromPlainText('Cyprus', 'Nicosia'),
    Flashcard.fromPlainText('Tunisia', 'Tunis'),
    Flashcard.fromPlainText('Qatar', 'Doha'),
    Flashcard.fromPlainText('Denmark', 'Copenhagen'),
    Flashcard.fromPlainText('Kosovo', 'Pristina'),
    Flashcard.fromPlainText('United Arab Emirates', 'Abu Dhabi'),
    Flashcard.fromPlainText('Austria', 'Vienna'),
    Flashcard.fromPlainText('Ireland', 'Dublin'),
    Flashcard.fromPlainText('Saint Kitts and Nevis', 'Basseterre'),
    Flashcard.fromPlainText('Chad', 'N\'Djamena'),
    Flashcard.fromPlainText('Antigua and Barbuda', 'Saint John\'s'),
    Flashcard.fromPlainText('Albania', 'Tirana (Tirane)'),
    Flashcard.fromPlainText('Chile', 'Santiago'),
    Flashcard.fromPlainText('Peru', 'Lima'),
    Flashcard.fromPlainText('Barbados', 'Bridgetown'),
    Flashcard.fromPlainText('Cuba', 'Havana'),
    Flashcard.fromPlainText('Germany', 'Berlin'),
    Flashcard.fromPlainText('Azerbaijan', 'Baku'),
    Flashcard.fromPlainText('Switzerland', 'Bern'),
    Flashcard.fromPlainText('Belgium', 'Brussels'),
    Flashcard.fromPlainText('Romania', 'Bucharest'),
    Flashcard.fromPlainText('Yemen', 'Sana\'a'),
    Flashcard.fromPlainText('Slovenia', 'Ljubljana'),
    Flashcard.fromPlainText('Algeria', 'Algiers'),
    Flashcard.fromPlainText('Japan', 'Tokyo'),
    Flashcard.fromPlainText('England[6]', 'London'),
    Flashcard.fromPlainText('Sri Lanka', 'Sri Jayawardenapura Kotte'),
    Flashcard.fromPlainText('Zambia', 'Lusaka'),
    Flashcard.fromPlainText('Lebanon', 'Beirut'),
    Flashcard.fromPlainText('North Korea', 'Pyongyang'),
    Flashcard.fromPlainText('Nicaragua', 'Managua'),
    Flashcard.fromPlainText('Türkiye (Turkey)[24]', 'Ankara'),
    Flashcard.fromPlainText('Liberia', 'Monrovia'),
    Flashcard.fromPlainText('Burkina Faso', 'Ouagadougou'),
    Flashcard.fromPlainText('Greece', 'Athens'),
    Flashcard.fromPlainText('Croatia', 'Zagreb'),
    Flashcard.fromPlainText('Rwanda', 'Kigali'),
    Flashcard.fromPlainText('Argentina', 'Buenos Aires'),
    Flashcard.fromPlainText('Vatican City', 'Vatican City'),
    Flashcard.fromPlainText('Northern Ireland[16]', 'Belfast'),
    Flashcard.fromPlainText('Uganda', 'Kampala'),
    Flashcard.fromPlainText('New Zealand', 'Wellington'),
    Flashcard.fromPlainText('Luxembourg', 'Luxembourg'),
    Flashcard.fromPlainText('Côte d\'Ivoire (Ivory Coast)', 'Yamoussoukro'),
    Flashcard.fromPlainText('Belarus', 'Minsk'),
    Flashcard.fromPlainText('Turkmenistan', 'Ashgabat'),
    Flashcard.fromPlainText('Slovakia', 'Bratislava'),
    Flashcard.fromPlainText('Iraq', 'Baghdad'),
    Flashcard.fromPlainText('Indonesia', 'Jakarta[9]'),
    Flashcard.fromPlainText('Gabon', 'Libreville'),
    Flashcard.fromPlainText('Trinidad and Tobago', 'Port of Spain'),
    Flashcard.fromPlainText('South Korea', 'Seoul'),
    Flashcard.fromPlainText('Colombia', 'Bogota'),
    Flashcard.fromPlainText('Comoros', 'Moroni'),
    Flashcard.fromPlainText('Laos', 'Vientiane'),
    Flashcard.fromPlainText('Brunei', 'Bandar Seri Begawan'),
    Flashcard.fromPlainText('Sao Tome and Principe', 'Sao Tome'),
    Flashcard.fromPlainText('China', 'Beijing'),
    Flashcard.fromPlainText('South Sudan', 'Juba'),
    Flashcard.fromPlainText('Bulgaria', 'Sofia'),
    Flashcard.fromPlainText('Taiwan[22]', 'Taipei'),
    Flashcard.fromPlainText('Palau', 'Melekeok'),
    Flashcard.fromPlainText('Ukraine', 'Kyiv or Kiev'),
    Flashcard.fromPlainText('Kazakhstan', 'Astana'),
    Flashcard.fromPlainText('Bangladesh', 'Dhaka'),
    Flashcard.fromPlainText('Nigeria', 'Abuja'),
    Flashcard.fromPlainText('Botswana', 'Gaborone'),
    Flashcard.fromPlainText('Armenia', 'Yerevan'),
    Flashcard.fromPlainText('San Marino', 'San Marino'),
    Flashcard.fromPlainText('Vanuatu', 'Port Vila'),
    Flashcard.fromPlainText('Portugal', 'Lisbon'),
    Flashcard.fromPlainText('Tanzania', 'Dodoma'),
    Flashcard.fromPlainText('Oman', 'Muscat'),
    Flashcard.fromPlainText('Marshall Islands', 'Majuro'),
    Flashcard.fromPlainText('Bahrain', 'Manama'),
    Flashcard.fromPlainText('Russia', 'Moscow'),
    Flashcard.fromPlainText('Malawi', 'Lilongwe'),
    Flashcard.fromPlainText('Nauru', 'No official capital'),
    Flashcard.fromPlainText('Somalia', 'Mogadishu'),
    Flashcard.fromPlainText('Italy', 'Rome'),
    Flashcard.fromPlainText('Fiji', 'Suva'),
    Flashcard.fromPlainText('Sudan', 'Khartoum'),
    Flashcard.fromPlainText('Monaco', 'Monaco'),
    Flashcard.fromPlainText('Mauritania', 'Nouakchott'),
    Flashcard.fromPlainText('Bolivia', 'La Paz (administrative), Sucre (official)'),
    Flashcard.fromPlainText('Vietnam', 'Hanoi'),
    Flashcard.fromPlainText('Jamaica', 'Kingston'),
  ];

  static Future createDeck() async{
    Deck sampleDeckCapitals = await Data.instance.createDeck(Deck(name: "Sample Deck - World Capital Cities", dateCreated:  DateTime.now()));

    for(int i = 0; i<capitalFlashcards.length; i++){
      Data.instance.createFlashcard(capitalFlashcards[i]);
      capitalFlashcards[i].deckID = sampleDeckCapitals.id;
    }
  }
}